# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lucene-Search-Highlight
version:      0.01
version_from: lib/Lucene/Search/Highlight.pm
installdirs:  site
requires:
    Lucene:                        0.07
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
